project:
  type: website
  render:
    - "*.qmd"
    - "!geoarrow/"

website:
  title: "GeoArrow"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - format.qmd
      - extension-types.qmd
      - text: "Implementations"
        menu:
          - href: https://github.com/geoarrow/geoarrow-c
            text: "C/C++"
          - href: https://github.com/kylebarron/geoarrow-rs
            text: "Rust"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
