project:
  type: website
  render:
    - "*.qmd"
    - "!geoarrow/"
    - "!geoarrow-data/"

website:
  title: "GeoArrow"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - format.qmd
      - extension-types.qmd
      - data.qmd
      - text: "Implementations"
        menu:
          - href: https://github.com/geoarrow/geoarrow-c
            text: "C/C++"
          - href: https://github.com/geoarrow/geoarrow-rs
            text: "Rust"
          - href: https://github.com/geoarrow/geoarrow-python
            text: "Python"
          - href: https://github.com/geoarrow/geoarrow-rs/blob/main/js/README.md
            text: "WebAssembly"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
