on:
  workflow_dispatch:
  push:
    branches: main

name: Render and Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Sync geoarrow/geoarrow
        run: |
          ./sync-external.sh
        env:
          GEOARROW_REF: "a7cc2392d3fb46e663d914d931f33d022dc45e91"
          GEOARROW_DATA_REF: "f8144731a6ef741de3cc41729e4ac21ae3b81209"

      - name: Publish to Netlify (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
